
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND ASSIGMENT BEGIN BEGINFOR BEGINIF BOOL CBOOL CINT CMBOOL CMINT COLON COMMA CONTINUE CVBOOL CVINT DENY END ENDFOR ENDIF EQ EXIT FALSE FOR FUNCTION GREATER IF INT INT_BIN INT_DEC LBRACKET LEFT LESS L_FIGBRACKET MBOOL MINT MINUS MOVE MUL_ELEM MUL_MATRIX NL PLUS RBRACKET RIGHT R_FIGBRACKET SPACE STL STR SUM TRANSPOSE TRUE VARIABLE VBOOL VINT WALLprogram : stmt_liststmt_list : stmt_list statement\n        | statementstatement : al_expression NLal_expression : INT_DEC PLUS INT_DEC\n        | INT_DEC MINUS INT_DEC'
    
_lr_action_items = {'INT_DEC':([0,2,3,6,7,8,9,],[5,5,-3,-2,-4,10,11,]),'$end':([1,2,3,6,7,],[0,-1,-3,-2,-4,]),'NL':([4,10,11,],[7,-5,-6,]),'PLUS':([5,],[8,]),'MINUS':([5,],[9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'stmt_list':([0,],[2,]),'statement':([0,2,],[3,6,]),'al_expression':([0,2,],[4,4,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> stmt_list','program',1,'p_program','parser.py',49),
  ('stmt_list -> stmt_list statement','stmt_list',2,'p_stmt_list','parser.py',60),
  ('stmt_list -> statement','stmt_list',1,'p_stmt_list','parser.py',61),
  ('statement -> al_expression NL','statement',2,'p_statement','parser.py',68),
  ('al_expression -> INT_DEC PLUS INT_DEC','al_expression',3,'p_al_expression','parser.py',72),
  ('al_expression -> INT_DEC MINUS INT_DEC','al_expression',3,'p_al_expression','parser.py',73),
]
